import { useState } from 'react'
import { Bell, ChevronRight, CircleDollarSign, ClipboardList, CreditCard, LayoutDashboard, Menu, Package, Plus, QrCode, ReceiptText, Settings, ShoppingBag, Store, UsersRound, WalletCards, X } from 'lucide-react'
import './MerchantView.css'

const navItems = [
  { id: 'home', label: 'ภาพรวมร้านค้า', icon: LayoutDashboard }, { id: 'pos', label: 'ขายหน้าร้าน (POS)', icon: CreditCard }, { id: 'payment', label: 'คิดเงินด่วน', icon: QrCode },
  { id: 'orders', label: 'ออเดอร์', icon: ClipboardList }, { id: 'inventory', label: 'สินค้า / สต็อก', icon: Package }, { id: 'reports', label: 'รายงานการเงิน', icon: ReceiptText },
  { id: 'wallet', label: 'กระเป๋าเงิน', icon: WalletCards }, { id: 'settings', label: 'ตั้งค่าร้านค้า', icon: Settings },
]
const products = [{ name: 'ชาไทยเย็น', sold: 42, amount: '฿2,940' }, { name: 'ครัวซองต์เนยสด', sold: 31, amount: '฿2,480' }, { name: 'อเมริกาโน่เย็น', sold: 28, amount: '฿1,960' }, { name: 'ขนมปังสังขยา', sold: 19, amount: '฿1,330' }]

export function MerchantView() {
  const [active, setActive] = useState('home')
  const [mobileOpen, setMobileOpen] = useState(false)
  const [notificationsOpen, setNotificationsOpen] = useState(false)
  const current = navItems.find((item) => item.id === active) ?? navItems[0]
  const navigate = (id: string) => { setActive(id); setMobileOpen(false) }
  const sidebar = <aside className="merchant-sidebar"><div className="merchant-brand"><div className="merchant-mark">CP</div><div><strong>ChatPOS</strong><span>MERCHANT PORTAL</span></div></div><div className="merchant-store"><Store size={16} /><div><span>สาขาปัจจุบัน</span><strong>ร้านกาแฟบ้านสวน</strong><small>สาขาหลัก · M-001</small></div><ChevronRight size={15} /></div><nav>{navItems.map(({ id, label, icon: NavIcon }) => <button className={active === id ? 'active' : ''} key={id} onClick={() => navigate(id)} type="button"><NavIcon size={17} /><span>{label}</span></button>)}</nav><div className="merchant-user"><div className="merchant-avatar">PB</div><div><strong>พิมพ์ชนก ศรีสุข</strong><span>Merchant Owner</span></div></div></aside>
  return <div className="merchant-app">{sidebar}{mobileOpen && <div className="merchant-mobile"><button className="merchant-backdrop" aria-label="ปิดเมนู" onClick={() => setMobileOpen(false)} type="button" /><div>{sidebar}<button className="merchant-close" aria-label="ปิดเมนู" onClick={() => setMobileOpen(false)} type="button"><X size={20} /></button></div></div>}<div className="merchant-main"><header className="merchant-topbar"><button className="merchant-menu-button" aria-label="เปิดเมนู" onClick={() => setMobileOpen(true)} type="button"><Menu size={20} /></button><div><p>Merchant Portal</p><h1>{current.label}</h1></div><div className="merchant-actions"><button aria-label="การแจ้งเตือน" className="merchant-icon-button" onClick={() => setNotificationsOpen((value) => !value)} type="button"><Bell size={18} /><b>3</b></button><div className="merchant-top-avatar">PB</div>{notificationsOpen && <div className="merchant-notifications"><strong>การแจ้งเตือน</strong><span>มีออเดอร์ใหม่ 4 รายการ</span><span>ยอดเงินเข้าวันนี้อัปเดตแล้ว</span></div>}</div></header><main className="merchant-content">{active === 'home' ? <MerchantHome onNavigate={navigate} /> : <MerchantSection active={active} label={current.label} />}</main></div></div>
}

function MerchantHome({ onNavigate }: { onNavigate: (id: string) => void }) { return <><section className="merchant-heading"><div><p className="merchant-eyebrow">GOOD MORNING, MERCHANT</p><h2>สวัสดีครับ ร้านกาแฟบ้านสวน</h2><p>ภาพรวมยอดขายและการดำเนินงานของร้านวันนี้</p></div><button className="merchant-primary" onClick={() => onNavigate('pos')} type="button"><Plus size={16} /> เปิดการขายหน้าร้าน</button></section><section className="merchant-metrics"><Metric icon={CircleDollarSign} label="ยอดขายวันนี้" value="฿18,450" detail="+12.8% จากเมื่อวาน" tone="green" /><Metric icon={ShoppingBag} label="ออเดอร์วันนี้" value="126" detail="18 รายการรอดำเนินการ" tone="blue" /><Metric icon={WalletCards} label="ยอดถอนได้" value="฿84,250" detail="อัปเดตล่าสุดเมื่อ 5 นาทีที่แล้ว" tone="violet" /><Metric icon={UsersRound} label="ลูกค้าสะสม" value="2,840" detail="เพิ่มขึ้น 36 คนในเดือนนี้" tone="amber" /></section><section className="merchant-grid"><article className="merchant-panel sales-panel"><div className="merchant-panel-heading"><div><h3>ยอดขายประจำสัปดาห์</h3><p>รายรับจากทุกช่องทาง</p></div><button className="merchant-link" onClick={() => onNavigate('reports')} type="button">ดูรายงาน <ChevronRight size={14} /></button></div><div className="sales-chart"><div className="chart-y"><span>20k</span><span>15k</span><span>10k</span><span>5k</span><span>0</span></div><div className="chart-bars">{[52, 70, 45, 82, 65, 91, 74].map((height, index) => <div className="chart-bar-column" key={index}><div className="chart-bar" style={{ height: `${height}%` }} /><span>{['จ.', 'อ.', 'พ.', 'พฤ.', 'ศ.', 'ส.', 'อา.'][index]}</span></div>)}</div></div></article><article className="merchant-panel"><div className="merchant-panel-heading"><div><h3>เมนูขายดี</h3><p>สินค้าที่มียอดขายสูงสุดวันนี้</p></div><Package size={18} className="merchant-green-text" /></div><div className="product-list">{products.map((product, index) => <div className="product-row" key={product.name}><span className="product-rank">0{index + 1}</span><div><strong>{product.name}</strong><span>ขายแล้ว {product.sold} รายการ</span></div><b>{product.amount}</b></div>)}</div></article></section><section className="merchant-actions-grid"><button onClick={() => onNavigate('payment')} type="button"><QrCode size={20} /><strong>สร้าง QR รับเงิน</strong><span>รับชำระเงินอย่างรวดเร็ว</span></button><button onClick={() => onNavigate('inventory')} type="button"><Package size={20} /><strong>จัดการสินค้า</strong><span>ดูสต็อกและเพิ่มรายการสินค้า</span></button><button onClick={() => onNavigate('wallet')} type="button"><WalletCards size={20} /><strong>ถอนเงิน</strong><span>ยอดพร้อมถอน ฿84,250</span></button></section></> }
function Metric({ icon: MetricIcon, label, value, detail, tone }: { icon: typeof CircleDollarSign; label: string; value: string; detail: string; tone: string }) { return <article className="merchant-metric"><div className={`merchant-metric-icon ${tone}`}><MetricIcon size={19} /></div><p>{label}</p><strong>{value}</strong><span>{detail}</span></article> }
function MerchantSection({ active, label }: { active: string; label: string }) { const content: Record<string, { title: string; description: string; icon: typeof Store }> = { pos: { title: 'ขายหน้าร้าน (POS)', description: 'เลือกสินค้าและสร้างรายการขายใหม่', icon: CreditCard }, payment: { title: 'คิดเงินด่วน', description: 'สร้าง QR หรือรับชำระเงินสำหรับออเดอร์', icon: QrCode }, orders: { title: 'ออเดอร์ทั้งหมด', description: 'ติดตามรายการสั่งซื้อและสถานะการชำระเงิน', icon: ClipboardList }, inventory: { title: 'สินค้าและสต็อก', description: 'จัดการรายการสินค้า ราคา และจำนวนคงเหลือ', icon: Package }, reports: { title: 'รายงานการเงิน', description: 'วิเคราะห์ยอดขายตามช่วงเวลาและช่องทาง', icon: ReceiptText }, wallet: { title: 'กระเป๋าเงิน', description: 'ยอดรายรับ ยอดถอนได้ และประวัติการถอนเงิน', icon: WalletCards }, settings: { title: 'ตั้งค่าร้านค้า', description: 'จัดการข้อมูลร้าน สาขา และสิทธิ์ทีมงาน', icon: Settings } }; const item = content[active] ?? { title: label, description: 'จัดการข้อมูลร้านค้าของคุณ', icon: Store }; const SectionIcon = item.icon; return <section className="merchant-placeholder"><div className="merchant-placeholder-icon"><SectionIcon size={28} /></div><p className="merchant-eyebrow">MERCHANT WORKSPACE</p><h2>{item.title}</h2><p>{item.description}</p><div className="merchant-demo-note"><Checkmark /> หน้านี้พร้อมต่อเข้ากับ workflow จาก apps/merchant และ API จริง</div></section> }
function Checkmark() { return <span className="merchant-check">✓</span> }
