import { useState } from 'react'
import { ArrowUpRight, CheckCircle2, ClipboardCheck, Clock3, Download, Filter, Search, ShieldAlert, Store, UsersRound, WalletCards } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import { mockAuditEvents, mockCases, mockRiskFlags, mockWithdrawals } from './mockData'

type PageViewsProps = { activePage: string }

const pageMeta: Record<string, { eyebrow: string; title: string; description: string }> = {
  'PD และพื้นที่': { eyebrow: 'PD OPERATIONS', title: 'PD และพื้นที่รับผิดชอบ', description: 'จัดการผู้ดูแลพื้นที่และสถานะการปฏิบัติงาน' },
  'ตัวแทน': { eyebrow: 'AGENT DIRECTORY', title: 'ตัวแทนทั้งหมด', description: 'ติดตาม Agent และสายงานที่รับผิดชอบ' },
  'Merchant Cases': { eyebrow: 'MERCHANT CASES', title: 'ร้านค้าและ Merchant Case', description: 'จัดการร้านค้าในเครือข่ายและสถานะการเชื่อมต่อ' },
  'คำขอเชื่อมร้าน': { eyebrow: 'ASSIGNMENT QUEUE', title: 'คำขอเชื่อมร้านกับ Agent', description: 'ตรวจสอบคำขอและการตอบรับ assignment' },
  'งาน KYC': { eyebrow: 'KYC WORK QUEUE', title: 'ตรวจสอบมาตรฐาน KYC', description: 'Admin ตรวจและ audit ทุกเคส โดย PD เป็นผู้อนุมัติขั้นสุดท้าย' },
  'Risk Control': { eyebrow: 'RISK CONTROL', title: 'Blacklist และ Fraud Flags', description: 'จัดการสัญญาณความเสี่ยงและรายการเฝ้าระวัง' },
  'การเงิน': { eyebrow: 'FINANCE CONTROL', title: 'Commission และ Withdrawal', description: 'ข้อมูล ledger และคิวรออนุมัติของ PD/Agent' },
  'Audit log': { eyebrow: 'AUDIT ACTIVITY', title: 'Audit Activity', description: 'ตรวจสอบประวัติการเปลี่ยนแปลงในระบบ' },
}

const rows = mockCases

export function PageViews({ activePage }: PageViewsProps) {
  const [query, setQuery] = useState('')
  const meta = pageMeta[activePage] ?? pageMeta['งาน KYC']
  const visibleRows = rows.filter((row) => `${row.name} ${row.detail}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="page-view"><section className="page-heading"><div><p className="eyebrow">{meta.eyebrow}</p><h1>{meta.title}</h1><p>{meta.description}</p></div><button className="primary-button" type="button"><Download size={15} />ส่งออก CSV</button></section>{activePage === 'การเงิน' ? <FinanceView /> : activePage === 'Risk Control' ? <RiskView /> : activePage === 'Audit log' ? <AuditView /> : <OperationalView activePage={activePage} query={query} setQuery={setQuery} rows={visibleRows} />}</div>
}

function OperationalView({ activePage, query, setQuery, rows: visibleRows }: { activePage: string; query: string; setQuery: (value: string) => void; rows: typeof rows }) {
  const isKyc = activePage === 'งาน KYC'
  const metrics: [string, string, string, LucideIcon][] = isKyc ? [['KYC ทั้งหมด', '286', 'blue', ClipboardCheck], ['รอตรวจ', '47', 'amber', Clock3], ['อนุมัติแล้ว', '198', 'green', CheckCircle2], ['ปฏิเสธ', '41', 'red', ShieldAlert]] : [['รายการทั้งหมด', '1,486', 'blue', UsersRound], ['กำลังใช้งาน', '1,302', 'green', ClipboardCheck], ['รอดำเนินการ', '84', 'amber', Clock3], ['อัปเดตวันนี้', '126', 'violet', ArrowUpRight]]
  return <><section className="metric-grid page-metrics">{metrics.map(([label, value, tone, MetricIcon]) => <article className="metric-card" key={String(label)}><div className={`metric-icon ${tone}`}><MetricIcon size={20} /><span className="sr-only">{label}</span></div><p>{label}</p><strong>{value}</strong><span>{isKyc ? 'จากข้อมูลทั้งหมดในระบบ' : 'ข้อมูลล่าสุดจากระบบ'}</span></article>)}</section><section className="panel work-panel"><div className="work-toolbar"><div><h2>{isKyc ? 'รายการ KYC ทั้งหมด' : 'รายการที่ต้องดำเนินการ'}</h2><p>ค้นหา กรอง และตรวจสอบรายละเอียดตามสิทธิ์ของคุณ</p></div><button className="filter-button" type="button"><Filter size={15} /> ตัวกรอง</button></div><div className="search-row"><div className="search-box"><Search size={16} /><input aria-label="ค้นหา" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ค้นหาชื่อ ร้าน รหัส หรือเบอร์โทร" /></div><select aria-label="กรองสถานะ" defaultValue=""><option value="">ทุกสถานะ</option><option>รอตรวจ</option><option>กำลังตรวจ</option><option>อนุมัติแล้ว</option></select></div><div className="table-scroll"><table><thead><tr><th>ชื่อ / รายละเอียด</th><th>ประเภท</th><th>สถานะ</th><th>อัปเดตล่าสุด</th><th /></tr></thead><tbody>{visibleRows.map((row) => <tr key={row.name}><td><strong>{row.name}</strong><span>{row.detail}</span></td><td>{row.type}</td><td><span className={`status-badge ${row.tone}`}><span />{row.status}</span></td><td className="muted">{row.time}</td><td className="action-cell"><button aria-label={`เปิด ${row.name}`} type="button"><ArrowUpRight size={16} /></button></td></tr>)}</tbody></table></div>{visibleRows.length === 0 && <div className="empty-state">ไม่พบข้อมูลตามคำค้นหา</div>}<div className="pagination"><span>แสดง {visibleRows.length} จาก 286 รายการ</span><button type="button">ก่อนหน้า</button><button className="current" type="button">1</button><button type="button">ถัดไป</button></div></section></>
}

function FinanceView() { const financeMetrics: [string, string, string, LucideIcon][] = [['Commission รวม', '฿1,284,600', 'blue', WalletCards], ['Direct Agent', '฿842,300', 'green', UsersRound], ['PD Benefit', '฿442,300', 'violet', Store], ['รออนุมัติถอน', '฿96,450', 'amber', Clock3]]; return <><section className="metric-grid page-metrics">{financeMetrics.map(([label, value, tone, FinanceIcon]) => <article className="metric-card" key={label}><div className={`metric-icon ${tone}`}><FinanceIcon size={20} /></div><p>{label}</p><strong>{value}</strong><span>เทียบกับรอบบัญชีล่าสุด</span></article>)}</section><section className="overview-grid"><article className="panel finance-summary"><div className="panel-heading"><div><h2>Commission ล่าสุด</h2><p>Ledger แบบ append-only</p></div><WalletCards className="panel-icon blue-text" size={20} /></div><div className="finance-bars"><Bar label="Agent commission" value="842,300" width="82%" tone="blue" /><Bar label="PD royalty" value="442,300" width="48%" tone="violet" /><Bar label="Pending withdrawal" value="96,450" width="20%" tone="amber" /></div></article><article className="panel"><div className="panel-heading"><div><h2>Withdrawal Queue</h2><p>รายการรออนุมัติ</p></div><Clock3 className="panel-icon amber-text" size={20} /></div><div className="queue-list">{mockWithdrawals.slice(0, 3).map((item) => <QueueItem key={item.name} name={item.name} amount={item.amount} />)}</div></article></section><section className="panel table-panel"><div className="panel-heading"><div><h2>รายการ Commission</h2><p>รายการเคลื่อนไหวล่าสุดใน ledger</p></div></div><div className="table-scroll"><table><thead><tr><th>ผู้รับผลประโยชน์</th><th>แหล่งที่มา</th><th>จำนวน</th><th>สถานะ</th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.name}><td><strong>{row.detail}</strong><span>{row.name}</span></td><td>Merchant case #{1200 + index}</td><td className="amount">฿{(index + 1) * 12500},.00</td><td><span className="status-badge approved"><span />paid</span></td></tr>)}</tbody></table></div></section></> }
function RiskView() { return <section className="risk-layout"><article className="panel risk-alert"><div className="risk-icon"><ShieldAlert size={24} /></div><div><h2>สัญญาณความเสี่ยงที่ต้องติดตาม</h2><p>มี {mockRiskFlags.length + 3} รายการที่ถูก flag ใน 24 ชั่วโมงล่าสุด ตรวจสอบก่อนดำเนินการต่อ</p></div></article><section className="metric-grid page-metrics"><article className="metric-card"><div className="metric-icon red"><ShieldAlert size={20} /></div><p>Fraud flags</p><strong>{mockRiskFlags.length + 3}</strong><span>เพิ่มขึ้น 2 รายการวันนี้</span></article><article className="metric-card"><div className="metric-icon amber"><Clock3 size={20} /></div><p>รอ review</p><strong>12</strong><span>ต้องมีผู้รับผิดชอบ</span></article></section><article className="panel"><div className="panel-heading"><div><h2>รายการเฝ้าระวัง</h2><p>ข้อมูลถูก mask ตาม permission</p></div></div><div className="risk-list">{mockRiskFlags.map((item) => <div className="risk-row" key={item}><ShieldAlert size={17} className="red-text" /><strong>{item}</strong><span className="status-badge risk"><span />ต้องตรวจสอบ</span></div>)}</div></article></section> }
function AuditView() { return <section className="panel audit-panel"><div className="panel-heading"><div><h2>ประวัติการทำรายการ</h2><p>ทุก action ถูกบันทึกพร้อมผู้ดำเนินการและ timestamp</p></div><button className="filter-button" type="button"><Filter size={15} /> กรองวันที่</button></div><div className="audit-list">{mockAuditEvents.map((item, index) => <div className="audit-row" key={item}><div className="audit-marker"><CheckCircle2 size={16} /></div><div><strong>{item}</strong><span>06 ส.ค. 2026 · {10 - index}:4{index} · Role protected</span></div><ArrowUpRight size={16} className="muted" /></div>)}</div></section> }
function Bar({ label, value, width, tone }: { label: string; value: string; width: string; tone: string }) { return <div className="bar-item"><div><span>{label}</span><strong>฿{value}</strong></div><div className="progress-track"><div className={`progress-fill ${tone}`} style={{ width }} /></div></div> }
function QueueItem({ name, amount }: { name: string; amount: string }) { return <div className="queue-row"><span>{name}</span><strong className="amber-text">{amount}</strong></div> }
